In [1]:
import numpy as np
import tensorflow as tf

In [2]:
w=tf.Variable(0,dtype=tf.float32)
cost=tf.add(tf.add(w**2,tf.multiply(-10.,w)),25)
train=tf.train.GradientDescentOptimizer(0.01).minimize(cost)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [3]:
init=tf.global_variables_initializer()
session=tf.Session()
session.run(init)
print(session.run(w))

0.0


In [4]:
session.run(train)
print(session.run(w))

0.099999994


In [5]:
#Lets run several times
for i in range(1000):
  session.run(train)
print(session.run(w))

4.999988


In [0]:
#what if the function is a function that depends on the training data
tf.reset_default_graph()
w=tf.Variable(0,dtype=tf.float32)
coefficient=np.array([[1.0],[-20.0],[100.0]])
x=tf.placeholder(tf.float32,shape=(3,1))
cost=x[0][0]*w**2+x[1][0]*w+x[2][0]
train=tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [7]:
init=tf.global_variables_initializer()
session=tf.Session()
session.run(init)
print(session.run(w))

0.0


In [8]:
session.run(train,feed_dict={x:coefficient})
print(session.run(w))

0.19999999


In [9]:
#Lets run several times
for i in range(1000):
  session.run(train,feed_dict={x:coefficient})
print(session.run(w))

9.999976


In [0]:
r = np.random.rand()
beta = 1-10**(- r - 1)

In [11]:
print(beta)

0.9850636899627101


In [0]:
tf.reset_default_graph()
yh=tf.constant(36,name='y_hat')
y=tf.constant(39,name='y')
loss=tf.Variable((y-yh)**2, name='loss')


In [13]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  print(sess.run(loss))

9


In [0]:
#Linear Function
#Y=WX+b
#W.shape=(4,3)
#X.shape=(3,1)
#b.shape=(4,1)
#For example X=tf.constant(np.random.randn(3,1),name="X")
def linear_function():
  np.random.seed(1)
  X=tf.constant(np.random.randn(3,1),name="X")
  W=tf.constant(np.random.randn(4,3),name="W")
  b=tf.constant(np.random.randn(4,1),name="b")
  Y=tf.add(tf.matmul(W,X),b)
  sess=tf.Session()
  result=sess.run(Y)

  return result

In [15]:
print( linear_function())

[[-2.15657382]
 [ 2.95891446]
 [-1.08926781]
 [-0.84538042]]


In [0]:
#Computing the sigmoid tf.sigmoid
#tf.softmax. 
#Lets compute the sigmoid for the inputs
#x=tf.placeholder(tf.float32,name="x")
#tf.sigmoid()
#sess.run(...,feed_dict={x=z})
def sigmoid(z):
  x=tf.placeholder(tf.float32, name="x")
  sigmoid=tf.sigmoid(x)
  with tf.Session() as sess:
    result=sess.run(sigmoid,feed_dict={x:z})
  return result

In [17]:
print(sigmoid(0))

0.5


In [18]:
print("sigmoid(12)= "+str(sigmoid(12)))

sigmoid(12)= 0.9999938


In [0]:
#Cross entropy
#tf.nn.sigmoid_cross_entropy_with_logits()
def cost(logits,labels):
  z=tf.placeholder(tf.float32,name="z")
  y=tf.placeholder(tf.float32,name="y")
  cost=tf.nn.sigmoid_cross_entropy_with_logits(logits=z,labels=y)
  sess=tf.Session()
  cost=sess.run(cost,feed_dict={z:logits, y:labels})
  sess.close()
  return cost

In [20]:
logits=np.array([0.2,0.4,0.7,0.9])
cost=cost(logits,np.array([0,0,1,1]))
print("cost= " +str(cost))

cost= [0.79813886 0.91301525 0.40318605 0.34115386]


In [0]:
def one_hot_matrix(labels,C):
  C=tf.constant(C,name='C')
  one_hot_matrix= tf.one_hot(labels, C, axis=0)
  sess=tf.Session()
  one_hot=sess.run(one_hot_matrix)
  sess.close()
  return one_hot

In [24]:
labels = np.array([1,2,3,0,2,1])
one_hot = one_hot_matrix(labels, C = 4)
print ("one_hot = \n" + str(one_hot))

one_hot = 
[[0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [0]:
def ones(shape):
  ones=tf.ones(shape)
  sess=tf.Session()
  ones=sess.run(ones)
  sess.close()
  return ones

In [26]:
print ("ones = " + str(ones([3])))

ones = [1. 1. 1.]
